#cloud-config
users:
        - name: terraria
packages:
        - unzip
runcmd:
        - apt-get install gnupg ca-certificates
        - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        - apt-get update
        - apt-get install -y mono-devel
        - wget -O /tmp/tshock.zip "https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip"
        - unzip /tmp/tshock.zip -d /home/terraria/tshock
        - chown -R terraria:terraria /home/terraria/tshock
        - curl "https://raw.githubusercontent.com/yi-jiayu/terraria-server/ce7babab9eae9c4d1b9da3014879ddf17c6bcfba/tshock.service" > /etc/systemd/system/tshock.service
        - systemd enable tshock
        - systemd start tshock
