#cloud-config
users:
  - name: terraria
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${ssh_public_key}
packages:
        - unzip
runcmd:
        - apt-get install gnupg ca-certificates
        - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        - apt-get update
        - apt-get install -y mono-devel
        - wget -P /home/terraria "https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip"
        - unzip /home/terraria/tshock_4.3.26.zip -d =home/terraria/tshock_4.3.26
